name: "Import data from Sensor Community"
run-name: "qr: Import sensor IDs: ${{ inputs.sensors }}, from ${{ inputs.start }} to  ${{ inputs.end }}"
on:
  workflow_dispatch:
    inputs:
      sensors:
        type: string
        description: "comma-separated list of sensor IDs, example: 62555,64255, if missing all"
        required: false
        default: ""
      start:
        type: date
        description: "start date (format 2024-12-27), if missing yesterday"
        required: false
        default: ""
      end:
        type: date
        description: "end date (format 2024-12-27), if missing yesterday"
        required: false
        default: ""
      include_registered_sensors:
        type: choice
        description: "include registered sensors (chip id not starting with _), if missing false"
        required: false
        default: 'false'
        options:
          - true
          - false
  schedule:
    - cron: "0 11 * * *"

jobs:
  import-sensor-community-daily-data:
    name: Import daily data from Sensor Community
    environment: legambiente-prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install InfluxDB client
        working-directory: ./sensorcommunity/dataingester
        shell: bash
        run: |
          echo -n "Install QuestDB Python module"
          sudo apt install python3-pip
          # use python3 --version to determine the specific version
          sudo apt install python3.12-venv
          python3 -m venv .venv
          .venv/bin/pip install questdb python-dateutil requests
      - name: Import daily data from Sensor Community for specific sensors
        working-directory: ./sensorcommunity/dataingester
        run: |
          source .venv/bin/activate
          ./import_data_by_date_range_questdb.py
        env:
          START: ${{ inputs.start }}
          END: ${{ inputs.end }}
          SENSORS: ${{ inputs.sensors }}
          INCLUDE_REGISTERED_SENSORS: ${{ include_registered_sensors }}
          QDB_TABLE: ${{ vars.QDB_TABLE }}
          QDB_CLIENT_CONF: ${{ secrets.QDB_CLIENT_CONF }}

